version: "2.1"

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2
executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  build-frontend:
    executor: ubuntu
    working_directory: ~/project/client
    steps:
      - checkout:
          path: ~/project
      - run: 
          command: |
            npm install
            npm run build
  build-server:
    executor: ubuntu
    working_directory: ~/project/
    steps:
      - checkout:
          path: ~/project
      - run: 
          command: |
            npm ci
            npm test
            npm run build --if-present
workflows:
  deploy:
    jobs:
      - build-frontend
      - build-server
      - heroku/deploy-via-git:
          force: true
          requires:
            - node/test
            - build-frontend
          filters:
            branches:
              only: master
