version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          force: true
          requires:
            - node/test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master 
