version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2

workflows:
  deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          force: true
          requires:
            - node/test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master
