name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build client
      working-directory: ./client
      run: |
        npm install
        npm run build
    - name: Build Server
      working-directory: /
      run: | 
        npm ci
        npm run build --if-present


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mon-petit-rpg" #Must be unique in Heroku
          heroku_email: "cohen.alberic@gmail.com"
